# -*- coding: utf-8 -*-
"""02 - Preprocesado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QsmBamY_Gjzmzy5MBHW1R-oiHPIamhD

# 02 - Preprocesado de Datos  
En este notebook se realiza el preprocesado del dataset de fútbol internacional entre 1872 y 2012, incluyendo:

1. Tratamiento de valores nulos  
2. Eliminación y análisis de duplicados  
3. Normalización de tipos  
4. Creación de columnas adicionales  
5. Preparación para modelos secuenciales
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

"""Se carga el .zip del dataset y se descomprime"""

uploaded = files.upload()
!unzip archive.zip

"""Se cargan los archivos del Dataset"""

df_results = pd.read_csv("results.csv")
df_goalscorers = pd.read_csv("goalscorers.csv")
df_former = pd.read_csv("former_names.csv")
df_shootouts = pd.read_csv("shootouts.csv")

"""Conversión de tipos de datos
Especialmente convertir la fecha a datetime
"""

df_results['date'] = pd.to_datetime(df_results['date'], errors = 'coerce')

#Otras columnas numericas
df_results['home_score'] = pd.to_numeric(df_results['home_score'], errors='coerce')
df_results['away_score'] = pd.to_numeric(df_results['away_score'], errors='coerce')

"""Tratamiento de valores nulos"""

print("Nulos por dataset:")
print(df_results.isnull().sum(), "\n")
print(df_goalscorers.isnull().sum(), "\n")
print(df_former.isnull().sum(), "\n")
print(df_shootouts.isnull().sum())

"""Limpieza Básica de nulos"""

# En results, no queremos perder información de fechas
df_results = df_results.dropna(subset=['date'])

# Rellenar campos de estadio cuando estén vacíos
df_results['city'] = df_results['city'].fillna('Unknown')
df_results['country'] = df_results['country'].fillna('Unknown')

# En goalscorers puede haber datos faltantes irrelevantes
df_goalscorers = df_goalscorers.dropna(subset=['scorer'])

# former_names — rellenar faltantes si existen (nuevo método)
df_former = df_former.ffill()

# shootouts — valores faltantes no afectan las columnas críticas
df_shootouts = df_shootouts.fillna("Unknown")

"""Eliminacion de duplicados"""

df_results = df_results.drop_duplicates()
df_goalscorers = df_goalscorers.drop_duplicates()
df_former = df_former.drop_duplicates()
df_shootouts = df_shootouts.drop_duplicates()

"""Creación de nuevas columnas

Año, Diferencia de goles, ganador, etc
"""

# Año del partido
df_results['year'] = df_results['date'].dt.year

# Diferencia de goles
df_results['goal_diff'] = df_results['home_score'] - df_results['away_score']

# Determinar ganador
def get_winner(row):
    if row.home_score > row.away_score:
        return row.home_team
    elif row.home_score < row.away_score:
        return row.away_team
    else:
        return "Draw"

df_results['winner'] = df_results.apply(get_winner, axis=1)

"""Unificación parcial de datasets"""

df_goalscorers['date'] = pd.to_datetime(df_goalscorers['date'], errors='coerce')
df_results['date'] = pd.to_datetime(df_results['date'], errors='coerce')

df_merged = df_goalscorers.merge(
    df_results,
    left_on=['date', 'team'],
    right_on=['date', 'home_team'],
    how='left'
)

df_merged.head()

"""Normalizacion de nombres de países

Esto evita problemas como USA vs United States
"""

df_results['home_team'] = df_results['home_team'].str.title()
df_results['away_team'] = df_results['away_team'].str.title()
df_former['current'] = df_former['current'].str.title()

"""Guardar Datasets Procesados

Estos archivos se van a usar en el notebook 3
"""

df_results.to_csv("results_clean.csv", index=False)
df_goalscorers.to_csv("goalscorers_clean.csv", index=False)
df_former.to_csv("former_names_clean.csv", index=False)
df_shootouts.to_csv("shootouts_clean.csv", index=False)

"""Descarga de los archivos generados"""

import shutil
import zipfile

zip_filename = "datasets_clean.zip"

with zipfile.ZipFile(zip_filename, 'w') as z:
    z.write("results_clean.csv")
    z.write("goalscorers_clean.csv")
    z.write("former_names_clean.csv")
    z.write("shootouts_clean.csv")

from google.colab import files
files.download(zip_filename)